#!/usr/bin/env bash
# setup-android-sdk.sh
# Install and configure the Android SDK + NDK required for UE5 Meta Quest builds.
#
# Usage:
#   ./scripts/setup-android-sdk.sh [--sdk-dir /path/to/sdk] [--ndk-version 25.2.9519653]
#
# Environment variables (override defaults):
#   ANDROID_SDK_ROOT   — where to install the SDK   (default: ~/Android/Sdk)
#   ANDROID_NDK_ROOT   — where to install the NDK   (default: $ANDROID_SDK_ROOT/ndk/<version>)
#   NDK_VERSION        — NDK version to install      (default: 25.2.9519653)
#   API_LEVEL          — Android API level           (default: 32)
#   BUILD_TOOLS_VER    — build-tools version         (default: 32.0.0)

set -euo pipefail

# -----------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}"
NDK_VERSION="${NDK_VERSION:-25.2.9519653}"
ANDROID_NDK_ROOT="${ANDROID_NDK_ROOT:-$ANDROID_SDK_ROOT/ndk/$NDK_VERSION}"
API_LEVEL="${API_LEVEL:-32}"
BUILD_TOOLS_VER="${BUILD_TOOLS_VER:-32.0.0}"
JAVA_MIN_VERSION=11

# -----------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
warn()  { echo "[WARN]  $*" >&2; }
error() { echo "[ERROR] $*" >&2; exit 1; }

require_cmd() {
    command -v "$1" &>/dev/null || error "Required command not found: $1 — install it first."
}

# -----------------------------------------------------------------------
# 1. Prerequisites
# -----------------------------------------------------------------------
info "Checking prerequisites..."
require_cmd java
require_cmd curl
require_cmd unzip

JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d. -f1)
[[ "$JAVA_VERSION" -ge "$JAVA_MIN_VERSION" ]] || \
    error "Java $JAVA_MIN_VERSION+ required, found Java $JAVA_VERSION"
info "Java $JAVA_VERSION OK"

# -----------------------------------------------------------------------
# 2. Download Command-Line Tools if not present
# -----------------------------------------------------------------------
CMDLINE_TOOLS_DIR="$ANDROID_SDK_ROOT/cmdline-tools/latest"
if [[ ! -f "$CMDLINE_TOOLS_DIR/bin/sdkmanager" ]]; then
    info "Downloading Android Command-Line Tools..."
    CMDLINE_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    TMP_ZIP=$(mktemp --suffix=.zip)
    curl -fsSL "$CMDLINE_URL" -o "$TMP_ZIP"
    mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
    unzip -q "$TMP_ZIP" -d "$ANDROID_SDK_ROOT/cmdline-tools"
    # Google packages as 'cmdline-tools/cmdline-tools' — rename to 'latest'
    mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$CMDLINE_TOOLS_DIR" 2>/dev/null || true
    rm -f "$TMP_ZIP"
    info "Command-line tools installed at $CMDLINE_TOOLS_DIR"
else
    info "Command-line tools already present."
fi

SDKMANAGER="$CMDLINE_TOOLS_DIR/bin/sdkmanager"

# -----------------------------------------------------------------------
# 3. Accept licences
# -----------------------------------------------------------------------
info "Accepting Android SDK licences..."
yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null 2>&1 || true

# -----------------------------------------------------------------------
# 4. Install SDK components
# -----------------------------------------------------------------------
info "Installing SDK platform API $API_LEVEL, build-tools $BUILD_TOOLS_VER, NDK $NDK_VERSION..."
"$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" \
    "platforms;android-$API_LEVEL" \
    "build-tools;$BUILD_TOOLS_VER" \
    "platform-tools" \
    "ndk;$NDK_VERSION"

# -----------------------------------------------------------------------
# 5. Write environment file
# -----------------------------------------------------------------------
ENV_FILE="$HOME/.config/1984-android-env.sh"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-android-sdk.sh — source this before building.
export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
export ANDROID_NDK_ROOT="$ANDROID_NDK_ROOT"
export ANDROID_HOME="$ANDROID_SDK_ROOT"
export PATH="\$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
EOF

info "Environment written to $ENV_FILE"
info "Add to your shell profile:  source $ENV_FILE"

# -----------------------------------------------------------------------
# 6. Verify ADB
# -----------------------------------------------------------------------
export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"
info "ADB version: $(adb version | head -1)"

info ""
info "=== Android SDK setup complete ==="
info "  SDK root : $ANDROID_SDK_ROOT"
info "  NDK root : $ANDROID_NDK_ROOT"
info "  API level: $API_LEVEL"
info ""
info "Next: point UE5 at this SDK."
info "  Edit → Project Settings → Platforms → Android SDK:"
info "    SDK API Level  : android-$API_LEVEL"
info "    NDK API Level  : android-$API_LEVEL"
info "    SDK path       : $ANDROID_SDK_ROOT"
info "    NDK path       : $ANDROID_NDK_ROOT"
